services:
  backend:
    build: ./backend
    platform: linux/amd64
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://db:27017/scentinel
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules: 